services:
  backend:
    build: ./backend
    env_file:
      - .env
    environment:
      APP_PORT: ${APP_PORT}
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${APP_PORT}:${APP_PORT}"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE: ${VITE_API_BASE}
    ports:
      - "8080:80"
    depends_on:
      - backend
