spring.application.name=demo

# AIVEN DATABASE (MYSQL)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# REQUIRED FOR RENDER
server.port=${PORT:8080}

# SECURITY (optional)
spring.security.user.name=admin
spring.security.user.password=admin123

# SSL (AIVEN)
spring.datasource.hikari.data-source-properties.sslMode=REQUIRED